import { TokenData } from "@/components/TokenCard";

// Helper function to generate random token data
const generateTokenData = (baseId: string, baseName: string, baseTicker: string, index: number): TokenData => {
  const ages = ['1s', '2s', '3s', '5s', '7s', '10s', '15s', '20s', '30s', '1m', '2m', '5m'];
  const marketCaps = ['$3.81K', '$6.14K', '$8.92K', '$12.5K', '$18.2K', '$24.1K', '$35.7K', '$42.3K', '$58.9K', '$67.4K'];
  const volumes = ['$0', '$437', '$706', '$1.2K', '$2.3K', '$3.5K', '$4.8K', '$6.1K', '$8.2K', '$9.7K'];
  const floors = ['0.017', '0.021', '0.023', '0.025', '0.028', '0.031', '0.035', '0.038', '0.042', '0.045'];
  
  return {
    id: `${baseId}${index}`,
    name: `${baseName} ${index}`,
    ticker: `${baseTicker}${index}`,
    age: ages[index % ages.length],
    marketCap: marketCaps[index % marketCaps.length],
    volume: volumes[index % volumes.length],
    floor: floors[index % floors.length],
    txCount: 2 + (index * 3) % 20,
    progress: 5 + (index * 7) % 90,
    holders: index % 15,
    comments: index % 8,
    bondingCurve: `${index % 50}/${100 + index * 10}`,
    hasAudit: index % 3 === 0,
    badges: index % 4 === 0 ? [{ type: "time", value: "23:59:55" }] : undefined,
    stats: [
      { icon: index % 2 === 0 ? "ri-fire-fill" : undefined, value: `${(index * 3) % 30}%`, color: index % 3 === 0 ? "green" : index % 3 === 1 ? "red" : "neutral" },
      { icon: index % 4 === 0 ? "ri-arrow-up-line" : index % 4 === 1 ? "ri-arrow-down-line" : undefined, value: index % 5 === 0 ? "DS" : `${(index * 2) % 25}%`, color: index % 3 === 0 ? "green" : index % 3 === 1 ? "red" : "neutral" },
      { value: index % 6 === 0 ? "ld" : `${index % 20}mo`, color: "neutral" },
      { icon: index % 5 === 0 ? "ri-arrow-up-line" : undefined, value: `${(index * 4) % 35}%`, color: index % 4 === 0 ? "green" : index % 4 === 1 ? "red" : "neutral" },
      { value: `${(index * 5) % 40}%`, color: "neutral" },
    ],
  };
};

export const newPairsTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`NP${i}...`, 'Token', 'TK', i)
).concat([
  {
    id: "6GZx...TS3V",
    name: "Meklo",
    ticker: "AHorse",
    age: "1s",
    marketCap: "$3.81K",
    volume: "$0",
    floor: "0.023",
    txCount: 3,
    progress: 15,
    holders: 0,
    comments: 0,
    bondingCurve: "2/247",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "23%", color: "green" },
      { value: "DS", color: "red" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "2WBR...NH8Y",
    name: "Meklo",
    ticker: "AHorse",
    age: "2s",
    marketCap: "$6.14K",
    volume: "$2K",
    floor: "0.025",
    txCount: 17,
    progress: 25,
    holders: 10,
    comments: 4,
    bondingCurve: "2/246",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "23%", color: "green" },
      { icon: "ri-arrow-up-line", value: "10%", color: "green" },
      { value: "ld", color: "neutral" },
      { icon: "ri-arrow-down-line", value: "23%", color: "red" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "8c1c...pump",
    name: "soltest",
    ticker: "solana testicel",
    age: "5s",
    marketCap: "$3.92K",
    volume: "$437",
    floor: "0.017",
    txCount: 8,
    progress: 12,
    holders: 3,
    comments: 1,
    bondingCurve: "0/1",
    hasAudit: true,
    badges: [{ type: "time", value: "23:59:55" }],
    stats: [
      { icon: "ri-fire-fill", value: "6%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "2sDz...pump",
    name: "Trump ICE",
    ticker: "Trump ICE Agent",
    age: "7s",
    marketCap: "$3.81K",
    volume: "$706",
    floor: "0.022",
    txCount: 14,
    progress: 18,
    holders: 0,
    comments: 0,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { value: "DS", color: "red" },
      { value: "21s", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "9kGe...bonk",
    name: "BARON",
    ticker: "Baron",
    age: "9s",
    marketCap: "$4.63K",
    volume: "$270",
    floor: "0.021",
    txCount: 2,
    progress: 8,
    holders: 1,
    comments: 1,
    bondingCurve: "21/12450",
    stats: [
      { icon: "ri-fire-fill", value: "6%", color: "green" },
      { icon: "ri-arrow-up-line", value: "6%", color: "green" },
      { value: "8mo", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "6%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "TSO...pump",
    name: "TSO",
    ticker: "Tobacco Smoking Onion",
    age: "10s",
    marketCap: "$3.81K",
    volume: "$0",
    floor: "0.023",
    txCount: 2,
    progress: 5,
    holders: 1,
    comments: 1,
    bondingCurve: "2/141",
    hasAudit: true,
    stats: [
      { value: "0%", color: "neutral" },
      { value: "12mo", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
]);

export const finalStretchTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`FS${i}...`, 'FinalToken', 'FT', i)
).concat([
  {
    id: "9aXv...7nNm",
    name: "Tesla AI",
    ticker: "Tesla AI",
    imageText: "T",
    age: "1h",
    marketCap: "$33.9K",
    volume: "$19K",
    floor: "0.025",
    txCount: 2536,
    progress: 85,
    holders: 205,
    comments: 2,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "31%", color: "green" },
      { value: "1h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "23%", color: "green" },
      { icon: "ri-arrow-up-line", value: "45%", color: "green" },
      { icon: "ri-arrow-up-line", value: "51%", color: "green" },
    ],
  },
  {
    id: "5ZKQ...BA4r",
    name: "IRAN",
    ticker: "Iranian Flag",
    age: "1m",
    marketCap: "$661K",
    volume: "$18K",
    floor: "0.029",
    txCount: 139,
    progress: 92,
    holders: 132,
    comments: 0,
    bondingCurve: "2033/2117",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "24d", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "HF6P...NSTU",
    name: "TATA",
    ticker: "The Alpha Deer",
    age: "2m",
    marketCap: "$644K",
    volume: "$18K",
    floor: "0.021",
    txCount: 173,
    progress: 78,
    holders: 139,
    comments: 0,
    bondingCurve: "485/554",
    badges: [{ type: "ld", value: "88" }],
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "6d", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "ESPP...79Uf",
    name: "ZAUTH",
    ticker: "zauthx402",
    age: "2m",
    marketCap: "$695K",
    volume: "$19K",
    floor: "0.023",
    txCount: 301,
    progress: 88,
    holders: 129,
    comments: 0,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "3m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "43vY...pump",
    name: "BROKE",
    ticker: "Fuck Around and Go Broke",
    age: "3d",
    marketCap: "$39.1K",
    volume: "$26K",
    floor: "0.83",
    txCount: 813,
    progress: 95,
    holders: 1049,
    comments: 34,
    bondingCurve: "0/3",
    badges: [{ type: "ld", value: "88" }],
    stats: [
      { icon: "ri-fire-fill", value: "58%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "51%", color: "green" },
      { icon: "ri-arrow-up-line", value: "15%", color: "green" },
      { value: "Paid", color: "paid" },
    ],
  },
  {
    id: "Goog...leAI",
    name: "Google",
    ticker: "Google AI",
    imageText: "G",
    age: "4h",
    marketCap: "$29.6K",
    volume: "$22K",
    floor: "0.022",
    txCount: 3639,
    progress: 72,
    holders: 203,
    comments: 0,
    bondingCurve: "1/3",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "22%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "5h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "40%", color: "green" },
      { icon: "ri-arrow-up-line", value: "46%", color: "green" },
    ],
  },
]);

export const migratedTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`MG${i}...`, 'MigratedToken', 'MT', i)
).concat([
  {
    id: "WoB5...FdZL",
    name: "SOL",
    ticker: "Sol The Trophy Tomato",
    imageText: "S",
    age: "29s",
    marketCap: "$36.4K",
    volume: "$0",
    floor: "0.021",
    txCount: 252,
    progress: 100,
    holders: 155,
    comments: 2,
    bondingCurve: "1/2",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "11%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "3m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "4%", color: "green" },
      { icon: "ri-arrow-up-line", value: "66%", color: "green" },
      { icon: "ri-arrow-up-line", value: "67%", color: "green" },
    ],
  },
  {
    id: "GCED...Me4T",
    name: "Horse",
    ticker: "The Horse",
    age: "1m",
    marketCap: "$105K",
    volume: "$5K",
    floor: "0.021",
    txCount: 127,
    progress: 100,
    holders: 3,
    comments: 0,
    bondingCurve: "1/2",
    stats: [
      { icon: "ri-fire-fill", value: "100%", color: "green" },
      { icon: "ri-arrow-up-line", value: "14%", color: "green" },
      { value: "7m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "13%", color: "green" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "14%", color: "green" },
    ],
  },
  {
    id: "7mQV...oM3H",
    name: "HORSE",
    ticker: "A HORSE",
    age: "1m",
    marketCap: "$51.4K",
    volume: "$13K",
    floor: "0.028",
    txCount: 85,
    progress: 100,
    holders: 36,
    comments: 0,
    bondingCurve: "10/20",
    stats: [
      { icon: "ri-fire-fill", value: "75%", color: "green" },
      { icon: "ri-arrow-up-line", value: "75%", color: "green" },
      { value: "1h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "75%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "FXtM...A2vW",
    name: "Horse",
    ticker: "Not Just a Horse",
    age: "1m",
    marketCap: "$55.3K",
    volume: "$14K",
    floor: "0.037",
    txCount: 72,
    progress: 100,
    holders: 30,
    comments: 0,
    bondingCurve: "1/1",
    stats: [
      { icon: "ri-fire-fill", value: "76%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "BgDR...iyrw",
    name: "HORSE",
    ticker: "A HORSE",
    age: "1m",
    marketCap: "$64.8K",
    volume: "$201K",
    floor: "19.53",
    txCount: 2449,
    progress: 100,
    holders: 377,
    comments: 258,
    bondingCurve: "20/3629",
    badges: [{ type: "ds", value: "DS" }],
    stats: [
      { icon: "ri-fire-fill", value: "22%", color: "green" },
      { value: "DS", color: "red" },
      { value: "3mo", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "7%", color: "green" },
      { icon: "ri-arrow-up-line", value: "42%", color: "green" },
    ],
  },
  {
    id: "Zama...5678",
    name: "Zama",
    ticker: "Zama",
    imageText: "Z",
    age: "2m",
    marketCap: "$1.49M",
    volume: "$29K",
    floor: "0.03",
    txCount: 1565,
    progress: 100,
    holders: 1155,
    comments: 2,
    bondingCurve: "1/2",
    stats: [
      { icon: "ri-fire-fill", value: "98%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "5m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "20%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
]);

export const bnbNewPairsTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`BNP${i}...`, 'BNBToken', 'BT', i)
).concat([
  {
    id: "0x12...abcd",
    name: "BNB Cat",
    ticker: "BNBCAT",
    age: "5s",
    marketCap: "$5.2K",
    volume: "$1K",
    floor: "0.001",
    txCount: 12,
    progress: 20,
    holders: 5,
    comments: 2,
    bondingCurve: "1/100",
    hasAudit: false,
    stats: [
      { icon: "ri-fire-fill", value: "15%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "0x34...efgh",
    name: "BNB Dog",
    ticker: "BNBDOG",
    age: "10s",
    marketCap: "$8.7K",
    volume: "$3K",
    floor: "0.002",
    txCount: 25,
    progress: 35,
    holders: 15,
    comments: 8,
    bondingCurve: "2/98",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "28%", color: "green" },
      { icon: "ri-arrow-up-line", value: "12%", color: "green" },
      { value: "ld", color: "neutral" },
      { icon: "ri-arrow-down-line", value: "5%", color: "red" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "0x56...ijkl",
    name: "BNB Frog",
    ticker: "BNBFROG",
    age: "15s",
    marketCap: "$12.1K",
    volume: "$5K",
    floor: "0.003",
    txCount: 40,
    progress: 50,
    holders: 22,
    comments: 12,
    bondingCurve: "3/97",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "35%", color: "green" },
      { icon: "ri-arrow-up-line", value: "18%", color: "green" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "8%", color: "green" },
    ],
  },
  {
    id: "0x78...mnop",
    name: "BNB Panda",
    ticker: "BNBPANDA",
    age: "20s",
    marketCap: "$15.3K",
    volume: "$7K",
    floor: "0.004",
    txCount: 55,
    progress: 65,
    holders: 28,
    comments: 15,
    bondingCurve: "4/96",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "42%", color: "green" },
      { icon: "ri-arrow-up-line", value: "22%", color: "green" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "12%", color: "green" },
    ],
  },
  {
    id: "0x9a...qrst",
    name: "BNB Tiger",
    ticker: "BNBTIGER",
    age: "25s",
    marketCap: "$18.9K",
    volume: "$9K",
    floor: "0.005",
    txCount: 68,
    progress: 75,
    holders: 35,
    comments: 18,
    bondingCurve: "5/95",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "48%", color: "green" },
      { icon: "ri-arrow-up-line", value: "28%", color: "green" },
      { value: "DS", color: "red" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "15%", color: "green" },
    ],
  },
  {
    id: "0xbc...uvwx",
    name: "BNB Elephant",
    ticker: "BNBELEPHANT",
    age: "30s",
    marketCap: "$22.4K",
    volume: "$11K",
    floor: "0.006",
    txCount: 78,
    progress: 85,
    holders: 42,
    comments: 22,
    bondingCurve: "6/94",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "55%", color: "green" },
      { icon: "ri-arrow-up-line", value: "32%", color: "green" },
      { value: "ld", color: "neutral" },
      { icon: "ri-arrow-down-line", value: "8%", color: "red" },
      { icon: "ri-arrow-up-line", value: "18%", color: "green" },
    ],
  },
]);

export const bnbFinalStretchTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`BFS${i}...`, 'BNBFinalToken', 'BFT', i)
).concat([
  {
    id: "0x78...mnop",
    name: "BNB Whale",
    ticker: "BNBWHALE",
    age: "30s",
    marketCap: "$45.6K",
    volume: "$18K",
    floor: "0.015",
    txCount: 85,
    progress: 85,
    holders: 45,
    comments: 20,
    bondingCurve: "15/85",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "65%", color: "green" },
      { icon: "ri-arrow-up-line", value: "25%", color: "green" },
      { value: "ld", color: "neutral" },
      { icon: "ri-arrow-down-line", value: "10%", color: "red" },
      { icon: "ri-arrow-up-line", value: "15%", color: "green" },
    ],
  },
  {
    id: "0x9a...qrst",
    name: "BNB Shark",
    ticker: "BNBSHARK",
    age: "45s",
    marketCap: "$67.3K",
    volume: "$25K",
    floor: "0.022",
    txCount: 120,
    progress: 92,
    holders: 68,
    comments: 35,
    bondingCurve: "22/78",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "78%", color: "green" },
      { icon: "ri-arrow-up-line", value: "32%", color: "green" },
      { value: "DS", color: "red" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "22%", color: "green" },
    ],
  },
  {
    id: "0xbc...uvwx",
    name: "BNB Dolphin",
    ticker: "BNBDOLPHIN",
    age: "1m",
    marketCap: "$89.1K",
    volume: "$32K",
    floor: "0.028",
    txCount: 145,
    progress: 95,
    holders: 85,
    comments: 42,
    bondingCurve: "28/72",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "82%", color: "green" },
      { icon: "ri-arrow-up-line", value: "38%", color: "green" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "28%", color: "green" },
    ],
  },
  {
    id: "0xde...yz01",
    name: "BNB Octopus",
    ticker: "BNBOCTOPUS",
    age: "1m 15s",
    marketCap: "$112.4K",
    volume: "$41K",
    floor: "0.035",
    txCount: 168,
    progress: 97,
    holders: 98,
    comments: 55,
    bondingCurve: "35/65",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "88%", color: "green" },
      { icon: "ri-arrow-up-line", value: "45%", color: "green" },
      { value: "DS", color: "red" },
      { icon: "ri-arrow-down-line", value: "12%", color: "red" },
      { icon: "ri-arrow-up-line", value: "32%", color: "green" },
    ],
  },
  {
    id: "0xf0...1234",
    name: "BNB Turtle",
    ticker: "BNBTURTLE",
    age: "1m 30s",
    marketCap: "$134.7K",
    volume: "$48K",
    floor: "0.042",
    txCount: 192,
    progress: 98,
    holders: 115,
    comments: 68,
    bondingCurve: "42/58",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "92%", color: "green" },
      { icon: "ri-arrow-up-line", value: "52%", color: "green" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "38%", color: "green" },
    ],
  },
]);

export const bnbMigratedTokens: TokenData[] = Array.from({ length: 30 }, (_, i) => 
  generateTokenData(`BMG${i}...`, 'BNBMigratedToken', 'BMT', i)
).concat([
  {
    id: "0x78...abcd",
    name: "BNB Panda",
    ticker: "BNBPANDA",
    age: "2m",
    marketCap: "$125K",
    volume: "$45K",
    floor: "0.05",
    txCount: 300,
    progress: 100,
    holders: 150,
    comments: 75,
    bondingCurve: "50/50",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "90%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "2m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "45%", color: "green" },
      { icon: "ri-arrow-up-line", value: "30%", color: "green" },
    ],
  },
  {
    id: "0xde...yz12",
    name: "BNB Tiger",
    ticker: "BNBTIGER",
    age: "5m",
    marketCap: "$200K",
    volume: "$80K",
    floor: "0.08",
    txCount: 500,
    progress: 100,
    holders: 250,
    comments: 120,
    bondingCurve: "80/20",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "95%", color: "green" },
      { value: "DS", color: "red" },
      { value: "5m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "55%", color: "green" },
      { icon: "ri-arrow-up-line", value: "40%", color: "green" },
    ],
  },
  {
    id: "0xf0...3456",
    name: "BNB Dragon",
    ticker: "BNBDRAGON",
    age: "10m",
    marketCap: "$350K",
    volume: "$120K",
    floor: "0.12",
    txCount: 800,
    progress: 100,
    holders: 400,
    comments: 200,
    bondingCurve: "120/880",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "98%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "10m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "65%", color: "green" },
      { icon: "ri-arrow-up-line", value: "50%", color: "green" },
    ],
  },
  {
    id: "0x12...5678",
    name: "BNB Phoenix",
    ticker: "BNBPHOENIX",
    age: "15m",
    marketCap: "$480K",
    volume: "$165K",
    floor: "0.15",
    txCount: 1100,
    progress: 100,
    holders: 550,
    comments: 280,
    bondingCurve: "150/850",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "99%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "15m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "75%", color: "green" },
      { icon: "ri-arrow-up-line", value: "60%", color: "green" },
    ],
  },
  {
    id: "0x34...9abc",
    name: "BNB Unicorn",
    ticker: "BNBUNICORN",
    age: "20m",
    marketCap: "$620K",
    volume: "$210K",
    floor: "0.18",
    txCount: 1350,
    progress: 100,
    holders: 680,
    comments: 350,
    bondingCurve: "180/820",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "99%", color: "green" },
      { value: "DS", color: "red" },
      { value: "20m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "85%", color: "green" },
      { icon: "ri-arrow-up-line", value: "70%", color: "green" },
    ],
  },
  {
    id: "0x56...def0",
    name: "BNB Griffin",
    ticker: "BNBGRIFFIN",
    age: "25m",
    marketCap: "$780K",
    volume: "$265K",
    floor: "0.22",
    txCount: 1600,
    progress: 100,
    holders: 820,
    comments: 420,
    bondingCurve: "220/780",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "99%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "25m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "95%", color: "green" },
      { icon: "ri-arrow-up-line", value: "80%", color: "green" },
    ],
  },
]);
