import { TokenData } from "@/components/TokenCard";

export const newPairsTokens: TokenData[] = [
  {
    id: "6GZx...TS3V",
    name: "Meklo",
    ticker: "AHorse",
    age: "1s",
    marketCap: "$3.81K",
    volume: "$0",
    floor: "0.023",
    txCount: 3,
    progress: 15,
    holders: 0,
    comments: 0,
    bondingCurve: "2/247",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "23%", color: "green" },
      { value: "DS", color: "red" },
      { value: "ld", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "2WBR...NH8Y",
    name: "Meklo",
    ticker: "AHorse",
    age: "2s",
    marketCap: "$6.14K",
    volume: "$2K",
    floor: "0.025",
    txCount: 17,
    progress: 25,
    holders: 10,
    comments: 4,
    bondingCurve: "2/246",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "23%", color: "green" },
      { icon: "ri-arrow-up-line", value: "10%", color: "green" },
      { value: "ld", color: "neutral" },
      { icon: "ri-arrow-down-line", value: "23%", color: "red" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "8c1c...pump",
    name: "soltest",
    ticker: "solana testicel",
    age: "5s",
    marketCap: "$3.92K",
    volume: "$437",
    floor: "0.017",
    txCount: 8,
    progress: 12,
    holders: 3,
    comments: 1,
    bondingCurve: "0/1",
    hasAudit: true,
    badges: [{ type: "time", value: "23:59:55" }],
    stats: [
      { icon: "ri-fire-fill", value: "6%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "2sDz...pump",
    name: "Trump ICE",
    ticker: "Trump ICE Agent",
    age: "7s",
    marketCap: "$3.81K",
    volume: "$706",
    floor: "0.022",
    txCount: 14,
    progress: 18,
    holders: 0,
    comments: 0,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { value: "DS", color: "red" },
      { value: "21s", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "9kGe...bonk",
    name: "BARON",
    ticker: "Baron",
    age: "9s",
    marketCap: "$4.63K",
    volume: "$270",
    floor: "0.021",
    txCount: 2,
    progress: 8,
    holders: 1,
    comments: 1,
    bondingCurve: "21/12450",
    stats: [
      { icon: "ri-fire-fill", value: "6%", color: "green" },
      { icon: "ri-arrow-up-line", value: "6%", color: "green" },
      { value: "8mo", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "6%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "TSO...pump",
    name: "TSO",
    ticker: "Tobacco Smoking Onion",
    age: "10s",
    marketCap: "$3.81K",
    volume: "$0",
    floor: "0.023",
    txCount: 2,
    progress: 5,
    holders: 1,
    comments: 1,
    bondingCurve: "2/141",
    hasAudit: true,
    stats: [
      { value: "0%", color: "neutral" },
      { value: "12mo", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
];

export const finalStretchTokens: TokenData[] = [
  {
    id: "9aXv...7nNm",
    name: "Tesla AI",
    ticker: "Tesla AI",
    imageText: "T",
    age: "1h",
    marketCap: "$33.9K",
    volume: "$19K",
    floor: "0.025",
    txCount: 2536,
    progress: 85,
    holders: 205,
    comments: 2,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "31%", color: "green" },
      { value: "1h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "23%", color: "green" },
      { icon: "ri-arrow-up-line", value: "45%", color: "green" },
      { icon: "ri-arrow-up-line", value: "51%", color: "green" },
    ],
  },
  {
    id: "5ZKQ...BA4r",
    name: "IRAN",
    ticker: "Iranian Flag",
    age: "1m",
    marketCap: "$661K",
    volume: "$18K",
    floor: "0.029",
    txCount: 139,
    progress: 92,
    holders: 132,
    comments: 0,
    bondingCurve: "2033/2117",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "24d", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "HF6P...NSTU",
    name: "TATA",
    ticker: "The Alpha Deer",
    age: "2m",
    marketCap: "$644K",
    volume: "$18K",
    floor: "0.021",
    txCount: 173,
    progress: 78,
    holders: 139,
    comments: 0,
    bondingCurve: "485/554",
    badges: [{ type: "ld", value: "88" }],
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "6d", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "ESPP...79Uf",
    name: "ZAUTH",
    ticker: "zauthx402",
    age: "2m",
    marketCap: "$695K",
    volume: "$19K",
    floor: "0.023",
    txCount: 301,
    progress: 88,
    holders: 129,
    comments: 0,
    bondingCurve: "0/1",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "3m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "19%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "43vY...pump",
    name: "BROKE",
    ticker: "Fuck Around and Go Broke",
    age: "3d",
    marketCap: "$39.1K",
    volume: "$26K",
    floor: "0.83",
    txCount: 813,
    progress: 95,
    holders: 1049,
    comments: 34,
    bondingCurve: "0/3",
    badges: [{ type: "ld", value: "88" }],
    stats: [
      { icon: "ri-fire-fill", value: "58%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "3%", color: "green" },
      { icon: "ri-arrow-up-line", value: "51%", color: "green" },
      { icon: "ri-arrow-up-line", value: "15%", color: "green" },
      { value: "Paid", color: "paid" },
    ],
  },
  {
    id: "Goog...leAI",
    name: "Google",
    ticker: "Google AI",
    imageText: "G",
    age: "4h",
    marketCap: "$29.6K",
    volume: "$22K",
    floor: "0.022",
    txCount: 3639,
    progress: 72,
    holders: 203,
    comments: 0,
    bondingCurve: "1/3",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "22%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "5h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "40%", color: "green" },
      { icon: "ri-arrow-up-line", value: "46%", color: "green" },
    ],
  },
];

export const migratedTokens: TokenData[] = [
  {
    id: "WoB5...FdZL",
    name: "SOL",
    ticker: "Sol The Trophy Tomato",
    imageText: "S",
    age: "29s",
    marketCap: "$36.4K",
    volume: "$0",
    floor: "0.021",
    txCount: 252,
    progress: 100,
    holders: 155,
    comments: 2,
    bondingCurve: "1/2",
    hasAudit: true,
    stats: [
      { icon: "ri-fire-fill", value: "11%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "3m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "4%", color: "green" },
      { icon: "ri-arrow-up-line", value: "66%", color: "green" },
      { icon: "ri-arrow-up-line", value: "67%", color: "green" },
    ],
  },
  {
    id: "GCED...Me4T",
    name: "Horse",
    ticker: "The Horse",
    age: "1m",
    marketCap: "$105K",
    volume: "$5K",
    floor: "0.021",
    txCount: 127,
    progress: 100,
    holders: 3,
    comments: 0,
    bondingCurve: "1/2",
    stats: [
      { icon: "ri-fire-fill", value: "100%", color: "green" },
      { icon: "ri-arrow-up-line", value: "14%", color: "green" },
      { value: "7m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "13%", color: "green" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "14%", color: "green" },
    ],
  },
  {
    id: "7mQV...oM3H",
    name: "HORSE",
    ticker: "A HORSE",
    age: "1m",
    marketCap: "$51.4K",
    volume: "$13K",
    floor: "0.028",
    txCount: 85,
    progress: 100,
    holders: 36,
    comments: 0,
    bondingCurve: "10/20",
    stats: [
      { icon: "ri-fire-fill", value: "75%", color: "green" },
      { icon: "ri-arrow-up-line", value: "75%", color: "green" },
      { value: "1h", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "75%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "FXtM...A2vW",
    name: "Horse",
    ticker: "Not Just a Horse",
    age: "1m",
    marketCap: "$55.3K",
    volume: "$14K",
    floor: "0.037",
    txCount: 72,
    progress: 100,
    holders: 30,
    comments: 0,
    bondingCurve: "1/1",
    stats: [
      { icon: "ri-fire-fill", value: "76%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
      { value: "0%", color: "neutral" },
    ],
  },
  {
    id: "BgDR...iyrw",
    name: "HORSE",
    ticker: "A HORSE",
    age: "1m",
    marketCap: "$64.8K",
    volume: "$201K",
    floor: "19.53",
    txCount: 2449,
    progress: 100,
    holders: 377,
    comments: 258,
    bondingCurve: "20/3629",
    badges: [{ type: "ds", value: "DS" }],
    stats: [
      { icon: "ri-fire-fill", value: "22%", color: "green" },
      { value: "DS", color: "red" },
      { value: "3mo", color: "neutral" },
      { value: "0%", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "7%", color: "green" },
      { icon: "ri-arrow-up-line", value: "42%", color: "green" },
    ],
  },
  {
    id: "Zama...5678",
    name: "Zama",
    ticker: "Zama",
    imageText: "Z",
    age: "2m",
    marketCap: "$1.49M",
    volume: "$29K",
    floor: "0.03",
    txCount: 1565,
    progress: 100,
    holders: 1155,
    comments: 2,
    bondingCurve: "1/2",
    stats: [
      { icon: "ri-fire-fill", value: "98%", color: "green" },
      { value: "0%", color: "neutral" },
      { value: "5m", color: "neutral" },
      { icon: "ri-arrow-up-line", value: "20%", color: "green" },
      { value: "0%", color: "neutral" },
    ],
  },
];
